__author__ = "Paul Schifferer <paul@schifferers.net>"

# SLACK_GITHUB_MAP_TABLE_NAME='slack_github'

# GITHUB_SECRET_TOKEN_ENV='GITHUB_SECRET_TOKEN'
SLACK_OAUTH_ACCESS_TOKEN_ENV = "SLACK_OAUTH_ACCESS_TOKEN"
SLACK_BOT_OAUTH_ACCESS_TOKEN_ENV = "SLACK_BOT_OAUTH_ACCESS_TOKEN"
SLACK_CLIENT_ID_ENV = "SLACK_CLIENT_ID"
SLACK_CLIENT_SECRET_ENV = "SLACK_CLIENT_SECRET"
SLACK_VERIFICATION_TOKEN_ENV = "SLACK_VERIFICATION_TOKEN"
SLACK_SIGNING_SECRET_ENV = "SLACK_SIGNING_SECRET"

SENTRY_DSN_ENV = "SENTRY_DSN"

MONGODB_URL_ENV = "MONGODB_URL"
